package main

import (
	"os"

	"github.com/C305DatabaseProject/database-project/backend"
	"github.com/gin-gonic/contrib/static"
	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"
)

func main() {
	err := godotenv.Load()
	if err != nil {
		panic("No .env file found.")
	}
	// Setup gin
	app := gin.Default()
	if os.Getenv("ENV") == "prod" {
		gin.SetMode(gin.ReleaseMode)
	} else {
		gin.SetMode(gin.DebugMode)
	}
	// Setup routes, serve static build files generated by React
	app.Use(static.Serve("/", static.LocalFile("./frontend/build", true)))
	backend.SetupRoutes(app)
	// Run locally with specified port inside .env
	app.Run("127.0.0.1:" + os.Getenv("PORT"))
}
